# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
